// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwbqwsaluwcdjoijcjuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3YnF3c2FsdXdjZGpvaWpjanVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Nzc2MzEsImV4cCI6MjA3MjM1MzYzMX0.HlSKSHe1MEcF4fuF4NoI5aBEenxi1K-iWFKeM7mhOQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});